### ISSUE TITLE
DNS verification fails for IP addresses.

### ISSUE THREAD

**Issue by rbroemeling** [fimmtiu/slow_query_exporter#4]
`invalid argument: --host '172.18.2.9' name resolution failed (DNS result has no information for 172.18.2.9)`

The hostname validation steps actually fails for addresses that are given as already-resolved IP addresses. Whoopsie.

**Comment by fimmtiu** [comment]
Fixed by ad110bdf737b401783e15ba08c37ff1c5a0e5857!
